### ISSUE TITLE
How to get mago3djs work?

### ISSUE THREAD

**Issue by mingweiLIU** [Gaia3D/mago3djs#395]
I found this very great project, and wanna to have a try, while I can't make it work, after I have converted the .ifc model to F4D format. I just don't know how could I load my custom data with mago3djs, and even don't know which page should I use to view the excamples after starting node server (seems the "cesium.html" under "\sample" folder is the demo page). Could someone help me with this?

**Comment by endofcap** [comment]
Have you tried this out? https://www.slideshare.net/endofcap/mago3d-technical-workshop-material

**Comment by cheonjeongdae** [comment]
Thank you for using mago3d.

Currently we are creating tutorials.
If you look at the tutorials directory
There is a # workshop-start.html file.
You can refer to two # json files in this file and modify the file.

1 workshop-policy-tutorials.json
  - You do not need to modify other settings.
    geo_init_latitude, geo_init_longitude
    Is the first loading point, please correct it.
2 workshop-data-tutorials.json
  - You need to mapping the converted data by running F4D Converter.
    If the converted data is F4D_Sample
    After F4D_ must be key and must be data_key of value.
   The two names must be the same.

    "Sample": {
                "data_key": "Sample",
                "data_name": "Bridge (は し)",
                "latitude": "35.6629",
                "longitude": "139.6843",
     }

**Comment by mingweiLIU** [comment]
Thanks a lot! it finally worked. Very great work! 
![image](https://user-images.githubusercontent.com/11702952/30999667-0c6e5b42-a509-11e7-82de-bc088d4bd70d.png)

**Comment by mingweiLIU** [comment]
The .ifc model converted from F4DConverter is too small, the unit is wrong?

**Comment by shire75** [comment]
The unit of converted result is meter.

And we've not got any kind of reports on unit scale factor issues yet.

We will test if you offer your test sample.

2017-09-29 14:20 GMT+09:00 mingweiLIU <notifications@github.com>:

**Comment by mingweiLIU** [comment]
Well of course yes! Here it is.
[AC11-Institute-Var-2-IFC.zip](https://github.com/Gaia3D/mago3djs/files/1343223/AC11-Institute-Var-2-IFC.zip)

**Comment by Yenseaon** [comment]
Deep impressed by the efficient work of mago3D

**Comment by cheonjeongdae** [comment]
We tried to convert and it seems to come out well.
![ac11-institute_front](https://user-images.githubusercontent.com/24997289/31003803-8df841c8-a52c-11e7-86a4-291cbfcbff3f.PNG)
![ac11-institute_indoor](https://user-images.githubusercontent.com/24997289/31003804-8e00fdea-a52c-11e7-8cb8-f464904b8a3a.PNG)

**Comment by mingweiLIU** [comment]
I am sorry, it was my carelessness. I copied the sample arguments from the F4DConverter readme file while the scale factor is 0.01.
![image](https://user-images.githubusercontent.com/11702952/31005168-29b91338-a52a-11e7-9d06-9ecbb74bc722.png)
