### ISSUE TITLE
cesium centerpoint error...

### ISSUE THREAD

**Issue by pikyst** [Gaia3D/mago3djs#396]
워크샵 샘플 파일을 통해 작동을 해봤는데 wordwind는 문제가 없지만
cesium에서 
Cesium.js:224918
An error occurred while rendering.  Rendering has stopped.
undefined
ReferenceError: centerPoint is not defined
이라는 에러와함께 맵을 가져오지 못하는데 어떤문제인지 알려주시면 감사하겠습니다..

**Comment by cheonjeongdae** [comment]
mago3djs 를 이용해 주셔서 감사 합니다.
말씀 하신 부분은 bug로 수정하여 릴리즈 하였습니다.
