### ISSUE TITLE
objectIndexFile.ihe can not  be found

### ISSUE THREAD

**Issue by Yenseaon** [Gaia3D/mago3djs#399]
I followed all the steps of your trainning materials ,but as the last step, I have some problems about loading the F4D,as the error  describe below:
![image](https://user-images.githubusercontent.com/29721016/31327659-49985228-ad03-11e7-932d-829a24280fd7.png)
but  I already have the ihe file 
![image](https://user-images.githubusercontent.com/29721016/31327683-64b40e26-ad03-11e7-8c74-ae583e91d844.png)
can anyone tell me what is the problem?

**Comment by Yenseaon** [comment]
My careless ， SO so sorry

**Comment by AnilGutha** [comment]
@Yenseaon, I'm also getting same issue. Could you please let me know what is that issue.
