### ISSUE TITLE
How can I select the whole object?

### ISSUE THREAD

**Issue by Yenseaon** [Gaia3D/mago3djs#417]
As I use your F4D format in mago3d,  I realise the selection of a chair is a only a bar, how I can select the whole chair instead of  the component of it? Thanks.（the picture of the question show below）
![image](https://user-images.githubusercontent.com/29721016/31492844-5cf176d2-af7f-11e7-9396-0acc81e36dd1.png)
![image](https://user-images.githubusercontent.com/29721016/31492908-960a9cbe-af7f-11e7-9ff4-8a42748c188e.png)

**Comment by cheonjeongdae** [comment]
After running the web server, connect to the following url
http: //localhost/sample/cesium.html

At the bottom left is a menu called 설정(Settings).
Click to expand the layer

# Selecting And Moving...... check Select All or Object
None, Select All, Object.

Please refer to the API for (English)
http://www.mago3d.com/homepage/api.do#changeMouseMoveAPI

**Comment by Yenseaon** [comment]
thanks a lot @cheonjeongdae ,but I may not describe my question well . I mean I want to  move the desk ,not the component of desk(pic 1 ). Or  we can say  I want to click the whole desk and highlight it not just the one part of it .How can I achieve that function? thanks.

![image](https://user-images.githubusercontent.com/29721016/31526772-8f5623f8-affb-11e7-9fbd-9ec1dc30fec0.png)
pic1: Selecting And Moving of Object  function can only select and  move the part of the desk not the whole desk and the ALL function will move the whole building . However ,I want to move the desk and highlight it .

**Comment by shire75** [comment]
Sorry for my late response.

Picking a group of objects is not supported in this version.

This functionality needs information about relationship or hierarchy among objects, and

that kind of information is dependent on business logic or data schema of a system

where mago3D is going to be inserted.

So, picking a bundle of objects is supported ONLY in case of customization.

If you have more questions, don't hesitate to ask us.

Thanks.

**Comment by Yenseaon** [comment]
thanks anyway @shire75   Looking forword for this function in the future mago3D
