### ISSUE TITLE
Can I change the rendering mode of a data_key in a Project?

### ISSUE THREAD

**Issue by Yenseaon** [Gaia3D/mago3djs#577]
I use the cesium demo, and find that I can change the rendering mode of  a Project by the API(changePropertyRenderingAPI), but I  also find that  I can only control the project layer (using projectId), I can not control the object(data_key)  show or not  in the project.Did I miss something ? Would you help me with the issue ,or can you  tell me how to achieve my goal?

**Comment by cheonjeongdae** [comment]
I do not know if I understood the question well.
project : data ...... 1 : N
data : object  ...... 1 :  N

data control
"isPhysical" : false ......... Hide
"isPhysical" : true  ......... Show

{
    //attributes area
    "attributes" : {
      "isPhysical" : false,
      "nodeType": "root",
      "projectType": "project Type"
    },
    //Child node area
    "children" : [
    ],
    //Location information area
    "data_key" : "Project name",
    "data_name" : "Project name"
}

There is no object control part yet.
Do you need this kind of api?
Specifically, how do you want to handle the object?
ex) changeColorAPI(managerFactoryInstance, projectId, dataKey, objectIds, property, color)

**Comment by Yenseaon** [comment]
![image](https://user-images.githubusercontent.com/29721016/38597705-d36915fa-3d8b-11e8-85ac-ed5e58642a65.png)
I mean  I can not control the part of data(red circle), I can only control the whole json file  show or not.

**Comment by cheonjeongdae** [comment]
죄송 합니다만
당신이 하고 싶은 것을 좀 더 구체적인 예를 들어서
설명해 주실수 없겠습니까?
ex)  data 를 투명하게 하고 싶다.
       drag 해서 지우고 싶다 등...

**Comment by gt1000** [comment]
Excuse me
For a more specific example of what you want to do
Could you please explain?
ex) I want to make the data transparent.
      I want to erase it by dragging etc ...

**Comment by Yenseaon** [comment]
By using changePropertyRenderingAPI I can only control the whole json file show or not.
For example I can use changePropertyRenderingAPI to show or hide "ifc_mep.json".
BUT a json file contain several  "children"， 
I want to use a button to control the "children"(which is one attributes in a json file) show or hide

**Comment by shire75** [comment]
Just make a json including only one data_key for which you want to control visualization.

※ 1 data_key == 1 F4D dataset.

**Comment by cheonjeongdae** [comment]
mago3d provides two version
1. mago3djs + converter
  Interworking with other business systems, mago3d is used as a pure 3d rendering engine
2. cms + converter
  - j2ee full package including various manager functions

json is in the same environment as local developer unit test or 1
It is a sample that business system has to export data in json format.
Format for communicating with mago3d

The feature you mentioned is in cms
project, data_info table
project ....  use_yn(column)
data_info ...... status(column)

When you modify a project or data in cms
Cache can be changed in real time.

**Comment by Yenseaon** [comment]
Thanks guys,I use @shire75 ' s method.
I also want to know  the meaning of the "property" in API-
function changePropertyRenderingAPI(managerFactoryInstance, isShow, projectId, property) 
  I find that in this function property can be any string format data,  even " ".

**Comment by shire75** [comment]
The parameter 'property' used in the function changePropertyRenderingAPI(managerFactoryInstance, isShow, projectId, property) is a condition defined by key/value attribute.
For example, if you call this function with property = 'isMain=false' and isShow=false, all F4D datasets in a json with attribute {"isMain" : false} disappear. 

So, if you want to show on/off for only 1 F4D, allocate a unique key/value attribute(like "thisBuildingSupportVisibilityControl" : true) on it and use this function with that key/value attribute.

**Comment by shire75** [comment]
Current format of the parameter, property, is ambiguous a little.
So, we have a plan to divide property into propertyKey and propertyValue in future upgrade.

**Comment by Yenseaon** [comment]
Thanks a lot , my problem is solved . I track the API and know the meaning of that function.
{
var splittedWords = property.split("=");
var propertyKey = splittedWords[0];
var propertyValue = splittedWords[1];
}
this parameter is really a little bit  ambiguous, I totally have no idea it need to be written in the format of 
 'isMain=ture'  and suggest you need a format examination for that 'input' .
Anyway, Thanks for your patience.
