### ISSUE TITLE
Error when I approach to see the model. DataStream is not defined

### ISSUE THREAD

**Issue by dcapeletti** [Gaia3D/mago3djs#644]
When I approach the model, the following error occurs:

```
An error occurred while rendering. Rendering has stopped.
ReferenceError: DataStream is not defined
ReferenceError: DataStream is not defined
    at Lego.parseLegoData (Shader.js:20672:15)
    at Lego.parseArrayBuffer (Shader.js:20523:7)
    at ParseQueue.parseArraySkins (Shader.js:26125:14)
    at MagoManager.manageQueue (Shader.js:10986:18)
    at MagoManager.startRender (Shader.js:9096:8)
    at MagoManager.start (Shader.js:8081:8)
    at executeCommands (http://localhost:8080/src/engine/cesium/Cesium.js:226607:35)
    at executeCommandsInViewport (http://localhost:8080/src/engine/cesium/Cesium.js:226966:9)
    at updateAndExecuteCommands (http://localhost:8080/src/engine/cesium/Cesium.js:226814:13)
    at render (http://localhost:8080/src/engine/cesium/Cesium.js:227350:9)
```
![error](https://user-images.githubusercontent.com/5890886/53097724-e59c2b00-3500-11e9-8015-fd635c7b3ded.png)

When I load cesium and navigate the balloon, it works well. The problem happens when I approach the model, nothing is loaded and the error appears immediately.

I hope you can help me. 
Thanks

**Comment by sdson** [comment]
Hola Diego.

Creo que no estas incluyendo todos las archivos JavaScript necesarios.

En la carpeta "sample" hay un archivo llamado "cesium.html". Es un ejemplo
de html para usar el Mago3D.
En dicho archivo, entre las lineas 951 y 1096 se decriben todos los
archivos JavaScript necesarios, y entre ellos esta:
<script type="text/javascript"
src="../src/mago3d/extern/DataStream.js"></script>

En cualquier caso haz un "copy" y "paste" de todo el bloque.

Saludos.

Atentamente Seongdo Son

PD:
Entre los dias 22/Febrero a 28/Febrero estoy en Singapur por cuestiones de
trabajo, por lo que en esos dias quizas no podre atenderte correctamente.
Luego cuando vuelva continuare atendiendote como siempre.



2019년 2월 20일 (수) 오후 11:18, Diego Ariel Capeletti <notifications@github.com>님이
작성:

**Comment by dcapeletti** [comment]
Hola Seongdo, gracias por la respuesta. El problema ha sido solucionado.

Creo que desde la primer versión que implementé esos archivos no estaban o no hacían falta porque mi implementación funcionaba sin ellos. De hecho mi html tiene los siguientes script de mago3d y funciona bien, no tengo conocimiento si debería crear enlaces a todos o no:

```
<link rel="stylesheet" href="../../src/engine/cesium/Widgets/widgets.css" />
<script type="text/javascript" src="../../externlib/jquery/jquery.js"></script>
<script type="text/javascript" src="../../src/engine/cesium/Cesium.js"></script>
<link rel="stylesheet" href="../../externlib/jquery-toast/jquery.toast.css" />
<script type="text/javascript" src="../../externlib/jquery-toast/jquery.toast.js"></script>
<script type="text/javascript" src="../../build/mago3d/mago3d.js"></script>
<script type="text/javascript" src="../../src/mago3d/extern/gl-matrix.js"></script>
<script type="text/javascript" src="../src/mago3d/extern/DataStream.js"></script>
```

Entonces para comprender mejor, entendiendo que todos los archivos .js que necesite mago3d estarán  disponibles en "cesium.html".  ¿Verdad?

PD: 
Que tengas un buen viaje y mucho éxitos con el negocio. Siempre ha sido muy cordial y puntual en las respuestas, me he sentido muy cómodo al respecto.

Saludos

**Comment by dcapeletti** [comment]
Para cerrar el tema, cuando llego a mis modelos, me aparece un Label CCTV9 que no se de dónde proviene. 

![cctv9](https://user-images.githubusercontent.com/5890886/53172439-1e510880-35c4-11e9-9c22-b0b325602bf9.png)


Quizás me podrías ayudar a entender como hacerla desaparecer esa etiqueta. Se que usando **changeLabelAPI** puedo mostrar u ocultar las mismas, pero debe haber código en algún archivo que me está mostrando algo que no está en mis modelos.

Gracias

**Comment by sdson** [comment]
Hola Diego.

Es extraño que aparezcan estos Labels, ya que son parte de un test que no
está habilitado en el código subido en el github.

Yo diría que estás ejecutando un código antiguo. Si pudiera ver tu html,
sólo la parte de la inclusión de los JavaScripts... ahí se habrá colado
algún test_cctv.

Atentamente Seongdo Son.

**Comment by dcapeletti** [comment]
Hola Seongdo, revisaré mis archivos e intentaré averiguar de dónde proviene dicho Label.

Gracias nuevamente
