### ISSUE TITLE
Can't Render IFC files

### ISSUE THREAD

**Issue by Carlxzw** [Gaia3D/mago3djs#774]
Hi guys.
I tried to run the mago3djs demo and using the cesium version, but I can't render my 3D data, neither this demo data.

> https://github.com/Gaia3D/mago3djs/files/2029661/demo_f4d.zip

What I can see are the bounding box and labels. So if there has any solution or self-check way, please do let know, thanks.

**Comment by JungHam** [comment]
@Carlxzw  Hello, I'm hyemi from Gaia3D. Is there any error message you can get from DevTools(if you use chrome) or the other developer console window? I think that problem can be occurred when you didn't put object index file at the right place.

**Comment by Carlxzw** [comment]
> @Carlxzw Hello, I'm hyemi from Gaia3D. Is there any error message you can get from DevTools(if you use chrome) or the other developer console window? I think that problem can be occurred when you didn't put object index file at the right place.

Hello, hyemi. Sorry to reply to you so late. The browser console does have some error message. It said 

> Uncaught (in promise) TypeError: Cannot read property 'setBoxSize' of undefined 

Is this error was caused by the reason that it can't find the object index file as you talked about ？And here are my project structure, did I put the object index file at the right place?
If it is not, where should I put it?
![image](https://user-images.githubusercontent.com/24801379/72321119-099ac900-36de-11ea-9d01-06813b05a4c5.png)

**Comment by Carlxzw** [comment]
> @Carlxzw Hello, I'm hyemi from Gaia3D. Is there any error message you can get from DevTools(if you use chrome) or the other developer console window? I think that problem can be occurred when you didn't put object index file at the right place.

Hello, hyemi. Sorry to reply to you so late. The browser console does have some error message. It said 

> Uncaught (in promise) TypeError: Cannot read property 'setBoxSize' of undefined 

Is this error was caused by the reason that it can't find the object index file as you talked about ？And here are my project structure, did I put the object index file at the right place?
If it is not, where should I put it?
![image](https://user-images.githubusercontent.com/24801379/72321359-a78e9380-36de-11ea-9c5f-1741011fd0f2.png)

**Comment by Carlxzw** [comment]
> @Carlxzw Hello, I'm hyemi from Gaia3D. Is there any error message you can get from DevTools(if you use chrome) or the other developer console window? I think that problem can be occurred when you didn't put object index file at the right place.

Hello, hyemi. Sorry to reply you so late. The browser console does have some error message. It said 

> Uncaught (in promise) TypeError: Cannot read property 'setBoxSize' of undefined 

Is this error was caused by the reason that it can't find the object index file as you talked about ？And here are my project structure, did I put the object index file at the right place? If it is not, where should I put it?
```
 mago3djs-master          
     └─f4d
         └─workshop
                 │─F4D_SOCIALROOM
                 │─F4D_STUDENTROOM
                 └─objectIndexFile.ihe
```

**Comment by JungHam** [comment]
Um....I think this problem occurs from the old code at master branch - We need to merge the develop branch to master branch but couldn't do that cause of the time matter, so would you like to use the code of the develop branch?

**Comment by JungHam** [comment]
And about the position of the object index file, if it is under the 'workhshop' directory then it is under the right position.

**Comment by Carlxzw** [comment]
> Um....I think this problem occurs from the old code at master branch - We need to merge the develop branch to master branch but couldn't do that cause of the time matter, so would you like to use the code of the develop branch?

As you said, I switched to develop branch and it works. It successfully renders models, including my own models. 
So thank you so much for answering my question.
