### ISSUE TITLE
about camera

### ISSUE THREAD

**Issue by thedevilsgrave** [Gaia3D/mago3djs#787]
How to control the initial position of the camera

**Comment by sdson** [comment]
Hi thedevildgrave.

you can control the initial camera position by modifiying the policy-cesium.json

...
 "geo_init_camera_enable": "true",
  "geo_init_latitude": "37.58210",
  "geo_init_longitude": "126.6113",
  "geo_init_height": "4000",
...

**Comment by thedevilsgrave** [comment]
I mean set the position of the camera after calling gotoProject()

**Comment by sdson** [comment]
You can use the "flyTo" method of cesium.  view.flyTo(...)

**Comment by thedevilsgrave** [comment]
I tried it, it didn't work

**Comment by kwunjaehyun** [comment]
Could i see some of your sources?

**Comment by thedevilsgrave** [comment]
This is the first time I tried it, maybe I haven’t understood. there is so many flyTo(),what we chose

**Comment by thedevilsgrave** [comment]
function initCamera() 
	{
		viewer.camera.flyTo({
			destination: Cesium.Cartesian3.fromDegrees(parseFloat(MagoConfig.getPolicy().geo_init_longitude),
				parseFloat(MagoConfig.getPolicy().geo_init_latitude),
				parseFloat(MagoConfig.getPolicy().geo_init_height)),
      duration: parseInt(MagoConfig.getPolicy().geo_init_duration),
      orientation: {
        heading: Cesium.Math.toRadians(0.0),
        pitch: Cesium.Math.toRadians(0.0),
        roll: 0.0
      }
		});
	}


Is it modified here？

**Comment by kwunjaehyun** [comment]
If you use mago3d on cesium,
i recommend to you, use Cesium Viewer instance', flyTo method. ( managerFactory.getViewer() )
second way, global method (in mago3d.js) gotoFlyAPI(managerFactory, longitude, latitude, height, duration).

I will try to help you.

**Comment by kwunjaehyun** [comment]
no source is maybe ok.

Did you have error message?

**Comment by thedevilsgrave** [comment]
No exception

**Comment by kwunjaehyun** [comment]
> No exception

Ok.
What is your needs?
1. when 3d globe(managerFactory make cesium globe) started, go to your goal position?
2. any time, go to some position?

**Comment by thedevilsgrave** [comment]
I need when 3d globle started,go to my position,and this time,The camera position is where I want.

**Comment by kwunjaehyun** [comment]
> I need when 3d globle started,go to my position,and this time,The camera position is where I want.

Start position managed policy object.
Just change value (in serverPolicy) your position.

managerFactory = new Mago3D.ManagerFactory(viewer, renderDivId, **serverPolicy**, projectIdArray, projectDataArray, projectDataFolderArray, imagePath);
-----------------------
 "geo_init_camera_enable": "true",
"geo_init_latitude": "37.58210",
"geo_init_longitude": "126.6113",
"geo_init_height": "4000",
-----------------------------

make viewer process is asynchronous, so you want change camera when globe started, 
ready magoManagerState to be READY(managerFactory.getMagoManagerState() === Mago3D.CODE.magoManagerState.READY)
and move camera. 

Unfortunately, I can't speak English, enough to explain to you.

**Comment by thedevilsgrave** [comment]
It doesn't matter, i hope it can help me

**Comment by thedevilsgrave** [comment]
I have last problem,The difference between flyTo() and setView()?If i change one,other also to change?

**Comment by kwunjaehyun** [comment]
> I have last problem,The difference between flyTo() and setView()?If i change one,other also to change?

I think,

If you wand move some position with animation effect, use flyTo().

just change camera position and orientation, use setView().

In mago3D JS, use setView when tracking node(F4D) only.

**Comment by thedevilsgrave** [comment]
> > I have last problem,The difference between flyTo() and setView()?If i change one,other also to change?
> 
> I think,
> 
> If you wand move some position with animation effect, use flyTo().
> 
> just change camera position and orientation, use setView().
> 
> In mago3D JS, use setView when tracking node(F4D) only.

감사합니다, 당신은 매우 열성적입니다

**Comment by kwunjaehyun** [comment]
> > > I have last problem,The difference between flyTo() and setView()?If i change one,other also to change?
> > 
> > 
> > I think,
> > If you wand move some position with animation effect, use flyTo().
> > just change camera position and orientation, use setView().
> > In mago3D JS, use setView when tracking node(F4D) only.
> 
> 감사합니다, 당신은 매우 열성적입니다

It's just my job. 

Thank you for your interest in mago3D JS.

谢谢。
