### ISSUE TITLE
How do I change the model size?

### ISSUE THREAD

**Issue by Miso0111** [Gaia3D/mago3djs#798]
![image](https://user-images.githubusercontent.com/77600884/104871556-53b82980-5986-11eb-9cc0-0a0fda18f551.png)
The size of the model does not match the size of the house in the base picture. How to reduce the size of the model?

**Comment by shire75** [comment]
Hi @Miso0111 

You can change model size with #usf(unit scale factor) argument when using the converter.

#usf value means the ratio of the length unit in original data file to 1 meter.

For example, if the length unit in a 3D file is mili-meter, you should use the converter with '#usf 0.001'.

**Comment by Miso0111** [comment]
I have successfully changed its size, thanks for your reply！

**Comment by Miso0111** [comment]
Hi @shire75
I have successfully changed its size. Thank you very much for your answer！
