### ISSUE TITLE
About the current camera perspective?

### ISSUE THREAD

**Issue by Miso0111** [Gaia3D/mago3djs#799]
Is there a way to get the position and rotation information of the current camera perspective

**Comment by sdson** [comment]
Hi Miso0111.

The camera's information is in Cesium. You can get the heading, pitch and roll and the position of the camera.

See the cesium API of camera.


Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Miso0111** [comment]
Ok,I see.Thank your very much for your answer!
